# https://cloud.google.com/appengine/docs/standard/python3/runtime#python-3.8
runtime: python38
instance_class: F1

# entrypoint is not neccesary because search for main.py in root with object app 
# entrypoint: gunicorn -b:$PORT falken_teleworking.main:app 
entrypoint: gunicorn -b:$PORT 'my_chispas:create_app()' # Beacause now is in the __init__.py file (https://docs.gunicorn.org/en/stable/run.html)
# No incluyas gunicorn en requirements.txt, a menos que especifiques el entrypoint

env_variables:
  ENV_PRO: "Y"
  LEVEL_LOG: "INFO, WARNING, ERROR"
  
handlers:
- url: /docs
  static_dir: docs

- url: /.*
  script: auto

includes:
- credentials.yaml